name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Install buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Build the image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: crates-build-env:latest
